export const achievementsData = [
  {
    id: 1,
    title: "15+ Years of Excellence",
    description: "Designing and operating technology systems since 2007.",
    icon: "🏆",
    value: "15+",
    label: "Years",
  },
  {
    id: 2,
    title: "National Scale Platforms",
    description: "Operators of multi-country 24/7 crisis response systems.",
    icon: "🌍",
    value: "5",
    label: "Countries",
  },
  {
    id: 3,
    title: "Health Records Digitized",
    description: "Managing and securing critical patient data through OPENHMIS.",
    icon: "📊",
    value: "50,000+",
    label: "Records",
  },
  {
    id: 4,
    title: "Monthly Crisis Calls",
    description: "Handling high-volume, mission-critical communications.",
    icon: "📞",
    value: "10,000+",
    label: "Monthly Calls",
  },
  {
    id: 5,
    title: "Financial Members Managed",
    description: "Optimizing operations for financial cooperatives.",
    icon: "👥",
    value: "5,000+",
    label: "Members",
  },
  {
    id: 6,
    title: "Verified Standards",
    description: "KDEAP Digital Assessment completed and UNICEF Venture Fund recipient.",
    icon: "✅",
    value: "100%",
    label: "Compliance",
  },
]
